"use client";
import { useMemo, useState } from "react";
import { toast } from "sonner";
import { Play, Plus, RotateCcw, X } from "lucide-react";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import type { EmployeeRecord } from "@/lib/employee-service";
const d = (e: EmployeeRecord, k: string) => String(e[k] ?? "").slice(0, 10);
const active = (e: EmployeeRecord) => String(e.status ?? "").toLowerCase() === "active";
const range = (v: string, f: string, t: string) => Boolean(v) && (!f || v >= f) && (!t || v <= t);
type K = "turnover" | "join" | "c30" | "c60" | "c90" | "hiring";
const names: Record<K, string> = { turnover: "Turnover Rate", join: "Join vs Resign", c30: "Contract Ending 0-30 Days", c60: "Contract Ending 31-60 Days", c90: "Contract Ending 61-90 Days", hiring: "Hiring Rate" };
const all = Object.keys(names) as K[];
export function KpiAnalyze({ employees }: { employees: EmployeeRecord[] }) {
  const [from, setFrom] = useState(""); const [to, setTo] = useState(""); const [picks, setPicks] = useState<K[]>([]); const [run, setRun] = useState(false);
  const rows = useMemo(() => employees.filter((e) => (!to || !d(e, "joinDate") || d(e, "joinDate") <= to) && (!from || !d(e, "exitDate") || d(e, "exitDate") >= from)), [employees, from, to]);
  const joined = rows.filter((e) => range(d(e, "joinDate"), from, to)).length; const resigned = rows.filter((e) => range(d(e, "exitDate"), from, to)).length; const opening = rows.filter((e) => (!from || !d(e, "joinDate") || d(e, "joinDate") < from) && (!from || !d(e, "exitDate") || d(e, "exitDate") >= from)).length; const closing = rows.filter((e) => (!to || !d(e, "joinDate") || d(e, "joinDate") <= to) && (!to || !d(e, "exitDate") || d(e, "exitDate") > to)).length; const avg = (opening + closing) / 2;
  const expiring = (min: number, max: number) => rows.filter((e) => { const end = ["contractCloseFirst", "contractCloseSecond", "contractCloseThird", "contractCloseFourth", "contractCloseFiveth"].map((k) => d(e, k)).filter(Boolean).sort()[0]; if (!end || !active(e)) return false; const start = new Date(to || new Date().toISOString().slice(0, 10)); const days = Math.ceil((new Date(end).getTime() - start.getTime()) / 86400000); return days >= min && days <= max; }).length;
  const add = () => { const k = all.find((x) => !picks.includes(x)); if (k) setPicks((p) => [...p, k]); };
  const canRun = Boolean(from || to || picks.length > 0); const runReport = () => { if (!canRun) { toast.error("Please select at least one date range or KPI before running the analysis."); return; } setRun(true); }; const clear = () => { setFrom(""); setTo(""); setPicks([]); setRun(false); };
  return <Card className="mt-5"><CardContent className="space-y-4 pt-4"><h3 className="text-sm font-semibold">KPI Analyze</h3><div className="flex flex-wrap items-end gap-2"><label className="text-xs">Date From<Input type="date" className="mt-1 h-8" value={from} onChange={(e) => setFrom(e.target.value)} /></label><label className="text-xs">Date To<Input type="date" className="mt-1 h-8" value={to} onChange={(e) => setTo(e.target.value)} /></label><Button size="sm" variant="outline" onClick={add} disabled={picks.length >= all.length}><Plus className="mr-1 size-3" />Add KPI</Button><Button size="sm" onClick={runReport}><Play className="mr-1 size-3" />Run</Button><Button size="sm" variant="outline" onClick={clear}><RotateCcw className="mr-1 size-3" />Clear</Button></div>{picks.map((key, i) => <div className="flex max-w-xl items-end gap-2" key={`${key}-${i}`}><label className="flex-1 text-xs">Filter KPI<select className="mt-1 h-8 w-full rounded-md border bg-background px-2 text-xs" value={key} onChange={(e) => setPicks((p) => p.map((x, n) => n === i ? e.target.value as K : x))}>{all.map((k) => <option key={k} value={k}>{names[k]}</option>)}</select></label><Button variant="ghost" size="icon" className="size-8" onClick={() => setPicks((p) => p.filter((_, n) => n !== i))}><X className="size-3" /></Button></div>)}{run && <div className="space-y-4">{picks.includes("turnover") && <KpiTable title={names.turnover} rows={[["Opening Employee", opening], ["Closing Employee", closing], ["Average Employee", avg], ["Total Resign", resigned]]} result={`${avg ? (resigned / avg * 100).toFixed(2) : "0.00"}%`} />}{picks.includes("join") && <KpiTable title={names.join} rows={[["New Join", joined], ["Total Resign", resigned]]} result={`Net Growth: ${joined - resigned}`} />}{picks.includes("c30") && <KpiTable title={names.c30} rows={[["Active Employee", rows.filter(active).length], ["Contract Ending 0-30 Days", expiring(0, 30)]]} result={`${expiring(0, 30)} employee`} />}{picks.includes("c60") && <KpiTable title={names.c60} rows={[["Active Employee", rows.filter(active).length], ["Contract Ending 31-60 Days", expiring(31, 60)]]} result={`${expiring(31, 60)} employee`} />}{picks.includes("c90") && <KpiTable title={names.c90} rows={[["Active Employee", rows.filter(active).length], ["Contract Ending 61-90 Days", expiring(61, 90)]]} result={`${expiring(61, 90)} employee`} />}{picks.includes("hiring") && <KpiTable title={names.hiring} rows={[["Total Applicant", "Applicant data not available"], ["Total Hired", "-"]]} result="Cannot be calculated yet" />}</div>}</CardContent></Card>;
}
function KpiTable({ title, rows, result }: { title: string; rows: [string, number | string][]; result: string }) { return <div className="w-fit max-w-full overflow-auto"><h4 className="mb-1 text-xs font-semibold">{title}</h4><table className="w-auto border-collapse text-xs"><tbody>{rows.map(([label, value]) => <tr key={label}><td className="border px-3 py-1 font-medium">{label}</td><td className="border px-3 py-1">{value}</td></tr>)}<tr className="bg-primary/10 font-bold"><td className="border px-3 py-1">Result / Rate</td><td className="border px-3 py-1">{result}</td></tr></tbody></table></div>; }
