import type { SimpleMasterCategory, LookupType } from "@/config/master-data-sheets";

/**
 * Minimal sample rows used to seed master data sheets ONLY when they are
 * completely empty (see lib/initialize-database.ts). Never overwrites
 * existing data. Kept intentionally small — just enough for the app to be
 * usable out of the box, not an exhaustive real-world dataset.
 */

interface SeedRow {
  code: string;
  name: string;
}

export const SIMPLE_MASTER_SEED: Record<SimpleMasterCategory, SeedRow[]> = {
  departments: [
    { code: "ACCOUNTING", name: "ACCOUNTING" },
    { code: "BUSINESS PROCESS", name: "BUSINESS PROCESS" },
    { code: "CUTTING", name: "CUTTING" },
    { code: "EXIM", name: "EXIM" },
    { code: "FINISHING", name: "FINISHING" },
    { code: "GENERAL AFFAIR", name: "GENERAL AFFAIR" },
    { code: "HELPER UMUM", name: "HELPER UMUM" },
    { code: "HRD & COMPLIANCE", name: "HRD & COMPLIANCE" },
    { code: "IE", name: "IE" },
    { code: "IT", name: "IT" },
    { code: "IT INVENTORY", name: "IT INVENTORY" },
    { code: "MANAGEMENT TRAINING", name: "MANAGEMENT TRAINING" },
    { code: "MD", name: "MD" },
    { code: "MECHANIC", name: "MECHANIC" },
    { code: "PPIC", name: "PPIC" },
    { code: "PURCHASING", name: "PURCHASING" },
    { code: "QA/QC", name: "QA/QC" },
    { code: "SAMPLE", name: "SAMPLE" },
    { code: "SAP", name: "SAP" },
    { code: "SEWING", name: "SEWING" },
    { code: "SEWING L 01", name: "SEWING L 01" },
    { code: "SEWING L 02", name: "SEWING L 02" },
    { code: "SEWING L 03", name: "SEWING L 03" },
    { code: "SEWING L 04", name: "SEWING L 04" },
    { code: "SEWING L 05", name: "SEWING L 05" },
    { code: "SEWING L 06", name: "SEWING L 06" },
    { code: "SEWING L 07", name: "SEWING L 07" },
    { code: "SEWING L 08", name: "SEWING L 08" },
    { code: "SEWING L 09", name: "SEWING L 09" },
    { code: "SEWING L 10", name: "SEWING L 10" },
    { code: "SEWING L 11", name: "SEWING L 11" },
    { code: "SEWING L 12", name: "SEWING L 12" },
    { code: "SEWING L 13", name: "SEWING L 13" },
    { code: "SEWING L 14", name: "SEWING L 14" },
    { code: "SEWING L 15", name: "SEWING L 15" },
    { code: "SEWING L 16", name: "SEWING L 16" },
    { code: "SEWING L 17", name: "SEWING L 17" },
    { code: "SEWING L 18", name: "SEWING L 18" },
    { code: "SEWING L 19", name: "SEWING L 19" },
    { code: "SEWING L 1A", name: "SEWING L 1A" },
    { code: "SEWING L 20", name: "SEWING L 20" },
    { code: "SEWING L 21", name: "SEWING L 21" },
    { code: "SEWING L 22", name: "SEWING L 22" },
    { code: "SEWING L 23", name: "SEWING L 23" },
    { code: "SEWING L 24", name: "SEWING L 24" },
    { code: "SEWING L 25", name: "SEWING L 25" },
    { code: "SEWING L 26", name: "SEWING L 26" },
    { code: "SEWING L 27", name: "SEWING L 27" },
    { code: "SEWING L 28", name: "SEWING L 28" },
    { code: "SEWING L 29", name: "SEWING L 29" },
    { code: "SEWING L 30", name: "SEWING L 30" },
    { code: "SEWING L 31", name: "SEWING L 31" },
    { code: "SEWING L 32", name: "SEWING L 32" },
    { code: "SEWING L 33", name: "SEWING L 33" },
    { code: "WAREHOUSE", name: "WAREHOUSE" },
    { code: "WFX", name: "WFX" },
  ],
  positions: [
    { code: "ACCOUNTING MANAGER", name: "ACCOUNTING MANAGER" },
    { code: "ACCOUNTING STAFF", name: "ACCOUNTING STAFF" },
    { code: "ADM FCA", name: "ADM FCA" },
    { code: "ADM JSS", name: "ADM JSS" },
    { code: "ADM PROD", name: "ADM PROD" },
    { code: "ADM QC FABRIC", name: "ADM QC FABRIC" },
    { code: "ADM QC FINISHING", name: "ADM QC FINISHING" },
    { code: "ADM QC FINISHING TARGET", name: "ADM QC FINISHING TARGET" },
    { code: "ADM SAMPLE", name: "ADM SAMPLE" },
    { code: "ADM WASHING", name: "ADM WASHING" },
    { code: "ADMIN EXIM", name: "ADMIN EXIM" },
    { code: "ADMINISTRATOR", name: "ADMINISTRATOR" },
    { code: "ASST MANAGER", name: "ASST MANAGER" },
    { code: "BANDKNIFE", name: "BANDKNIFE" },
    { code: "BARTEX", name: "BARTEX" },
    { code: "BOILER OPERATOR", name: "BOILER OPERATOR" },
    { code: "BRAND TECH MANAGER", name: "BRAND TECH MANAGER" },
    { code: "BUNDLING", name: "BUNDLING" },
    { code: "BUSINESS PROCESS STAFF", name: "BUSINESS PROCESS STAFF" },
    { code: "BUTTONHOLE", name: "BUTTONHOLE" },
    { code: "BUTTONHOLE  STAFF", name: "BUTTONHOLE  STAFF" },
    { code: "BUTTONHOLE OPR", name: "BUTTONHOLE OPR" },
    { code: "CAD ROOM OPERATOR", name: "CAD ROOM OPERATOR" },
    { code: "CHIEF", name: "CHIEF" },
    { code: "CHIEF MECHANIC", name: "CHIEF MECHANIC" },
    { code: "CHIEF QA", name: "CHIEF QA" },
    { code: "CLEANING SERVICE", name: "CLEANING SERVICE" },
    { code: "CMT & TECHNICAL", name: "CMT & TECHNICAL" },
    { code: "CUTTER", name: "CUTTER" },
    { code: "CUTTER  SAMPLE", name: "CUTTER  SAMPLE" },
    { code: "CUTTER PLANNER", name: "CUTTER PLANNER" },
    { code: "CUTTING SUPERVISOR", name: "CUTTING SUPERVISOR" },
    { code: "DRIVER", name: "DRIVER" },
    { code: "ELECTRICAL", name: "ELECTRICAL" },
    { code: "ELECTRICAL STAFF", name: "ELECTRICAL STAFF" },
    { code: "EXIM MANAGER", name: "EXIM MANAGER" },
    { code: "EXIM STAFF", name: "EXIM STAFF" },
    { code: "FCA A&F", name: "FCA A&F" },
    { code: "FCA AEO", name: "FCA AEO" },
    { code: "FCA ANN TAYLOR", name: "FCA ANN TAYLOR" },
    { code: "FCA CHICOS", name: "FCA CHICOS" },
    { code: "FCA EXPRESS", name: "FCA EXPRESS" },
    { code: "FCA GIII", name: "FCA GIII" },
    { code: "FCA HOLLISTER", name: "FCA HOLLISTER" },
    { code: "FCA MACY'S", name: "FCA MACY'S" },
    { code: "FCA NORDSTROM", name: "FCA NORDSTROM" },
    { code: "FIN CHIEF", name: "FIN CHIEF" },
    { code: "FIN MANAGER", name: "FIN MANAGER" },
    { code: "FIN SUPERVISOR", name: "FIN SUPERVISOR" },
    { code: "FINISH PATTERN FOR BULK", name: "FINISH PATTERN FOR BULK" },
    { code: "FOLDING", name: "FOLDING" },
    { code: "FOLDING & HANGTAG", name: "FOLDING & HANGTAG" },
    { code: "FUSING", name: "FUSING" },
    { code: "GENERAL ADMIN", name: "GENERAL ADMIN" },
    { code: "GENERAL MANAGER HRD", name: "GENERAL MANAGER HRD" },
    { code: "HANG TAG", name: "HANG TAG" },
    { code: "HELPER", name: "HELPER" },
    { code: "HELPER JSS", name: "HELPER JSS" },
    { code: "HELPER SAMPLE", name: "HELPER SAMPLE" },
    { code: "HOOK", name: "HOOK" },
    { code: "HRD COMPLIANCE STAFF", name: "HRD COMPLIANCE STAFF" },
    { code: "HRD MANAGER", name: "HRD MANAGER" },
    { code: "HRD STAFF", name: "HRD STAFF" },
    { code: "IE ADM OPR", name: "IE ADM OPR" },
    { code: "IE ADMIN", name: "IE ADMIN" },
    { code: "IE ASSISTANT", name: "IE ASSISTANT" },
    { code: "IE CHIEF", name: "IE CHIEF" },
    { code: "IE STAFF", name: "IE STAFF" },
    { code: "IRONING", name: "IRONING" },
    { code: "IRONING / PRESSING", name: "IRONING / PRESSING" },
    { code: "IT INVENTORY STAFF", name: "IT INVENTORY STAFF" },
    { code: "IT STAFF", name: "IT STAFF" },
    { code: "JSS HELPER", name: "JSS HELPER" },
    { code: "JSS IRONING / PRESSING", name: "JSS IRONING / PRESSING" },
    { code: "JSS OPERATOR", name: "JSS OPERATOR" },
    { code: "JSS STAFF", name: "JSS STAFF" },
    { code: "JSS SUPERVISOR", name: "JSS SUPERVISOR" },
    { code: "LEADER/ ASISTANT", name: "LEADER/ ASISTANT" },
    { code: "LEADER/ ASISTANT BUTTON FINISHING", name: "LEADER/ ASISTANT BUTTON FINISHING" },
    { code: "LEADER/ ASISTANT IRONING / PRESSING", name: "LEADER/ ASISTANT IRONING / PRESSING" },
    { code: "LEADER/ ASISTANT PACKING", name: "LEADER/ ASISTANT PACKING" },
    { code: "LEADER/ ASISTANT QA FINISHING", name: "LEADER/ ASISTANT QA FINISHING" },
    { code: "LEADER/ASSIST PACKING", name: "LEADER/ASSIST PACKING" },
    { code: "LEADER/ASSIST SUPERVISOR", name: "LEADER/ASSIST SUPERVISOR" },
    { code: "LEADER/ASSIST SUPERVISOR JSS", name: "LEADER/ASSIST SUPERVISOR JSS" },
    { code: "LILIT", name: "LILIT" },
    { code: "LOADING", name: "LOADING" },
    { code: "LOADING + TRANSFER FABRIC", name: "LOADING + TRANSFER FABRIC" },
    { code: "MAIN SAMPLING SUPERVISOR", name: "MAIN SAMPLING SUPERVISOR" },
    { code: "MAINTENANCE", name: "MAINTENANCE" },
    { code: "MAINTENANCE SPV", name: "MAINTENANCE SPV" },
    { code: "MANAGEMENT TRAINING", name: "MANAGEMENT TRAINING" },
    { code: "MANAGER", name: "MANAGER" },
    { code: "MARKER 3D", name: "MARKER 3D" },
    { code: "MARKER MAKER", name: "MARKER MAKER" },
    { code: "MARKING", name: "MARKING" },
    { code: "MD ADMIN STAFF", name: "MD ADMIN STAFF" },
    { code: "MD STAFF", name: "MD STAFF" },
    { code: "MECHANIC SUPERVISOR", name: "MECHANIC SUPERVISOR" },
    { code: "MEKANIK STAFF", name: "MEKANIK STAFF" },
    { code: "METAL DETECTOR", name: "METAL DETECTOR" },
    { code: "MT STAFF", name: "MT STAFF" },
    { code: "NUMBERING", name: "NUMBERING" },
    { code: "NURSE", name: "NURSE" },
    { code: "OPERATOR", name: "OPERATOR" },
    { code: "OPERATOR GPT", name: "OPERATOR GPT" },
    { code: "OPERATOR L 29", name: "OPERATOR L 29" },
    { code: "OPERATOR L 30", name: "OPERATOR L 30" },
    { code: "OPERATOR SEWING SAMPLE", name: "OPERATOR SEWING SAMPLE" },
    { code: "PACKING", name: "PACKING" },
    { code: "PAINTING", name: "PAINTING" },
    { code: "PAINTING / SERAT", name: "PAINTING / SERAT" },
    { code: "PANTRY", name: "PANTRY" },
    { code: "PATTERN CHECKER", name: "PATTERN CHECKER" },
    { code: "PATTERN MARKER", name: "PATTERN MARKER" },
    { code: "PATTERN MEASUREMENT MAKING", name: "PATTERN MEASUREMENT MAKING" },
    { code: "PIPING", name: "PIPING" },
    { code: "POLA / PATTERN COMPUTER", name: "POLA / PATTERN COMPUTER" },
    { code: "POLA FINISH", name: "POLA FINISH" },
    { code: "POLA MARKER", name: "POLA MARKER" },
    { code: "PPIC ADMIN", name: "PPIC ADMIN" },
    { code: "PPIC MANAGER", name: "PPIC MANAGER" },
    { code: "PPIC SAMPLE", name: "PPIC SAMPLE" },
    { code: "PPIC STAFF", name: "PPIC STAFF" },
    { code: "PROD. MANAGER", name: "PROD. MANAGER" },
    { code: "PRODUKSI MANAGER", name: "PRODUKSI MANAGER" },
    { code: "PSO OPR", name: "PSO OPR" },
    { code: "PURCHASING OPR", name: "PURCHASING OPR" },
    { code: "PURCHASING STAFF", name: "PURCHASING STAFF" },
    { code: "QA ADMIN", name: "QA ADMIN" },
    { code: "QA ASSISTANT MANAGER", name: "QA ASSISTANT MANAGER" },
    { code: "QA CUTTING CHIEF", name: "QA CUTTING CHIEF" },
    { code: "QA CUTTING SPV", name: "QA CUTTING SPV" },
    { code: "QA CUTTING STAFF", name: "QA CUTTING STAFF" },
    { code: "QA FABRIC INSPECTION", name: "QA FABRIC INSPECTION" },
    { code: "QA FABRIC LAB", name: "QA FABRIC LAB" },
    { code: "QA FABRIC STAFF", name: "QA FABRIC STAFF" },
    { code: "QA FINISHING SPV", name: "QA FINISHING SPV" },
    { code: "QA INTERNAL AUDITOR", name: "QA INTERNAL AUDITOR" },
    { code: "QA MANAGER", name: "QA MANAGER" },
    { code: "QA NOMINATE STAFF", name: "QA NOMINATE STAFF" },
    { code: "QA SAMPLE STAFF", name: "QA SAMPLE STAFF" },
    { code: "QA SEWING", name: "QA SEWING" },
    { code: "QA SEWING SPV", name: "QA SEWING SPV" },
    { code: "QA SPV FABRIC", name: "QA SPV FABRIC" },
    { code: "QA SUBCON STAFF", name: "QA SUBCON STAFF" },
    { code: "QA TOP SAMPLE", name: "QA TOP SAMPLE" },
    { code: "QC 7PCS AUDITOR (SEWING & FIN)", name: "QC 7PCS AUDITOR (SEWING & FIN)" },
    { code: "QC ACCESSORIES", name: "QC ACCESSORIES" },
    { code: "QC ACCURASY", name: "QC ACCURASY" },
    { code: "QC AFTER WASH BEFORE IRON", name: "QC AFTER WASH BEFORE IRON" },
    { code: "QC AUDIT", name: "QC AUDIT" },
    { code: "QC AUDIT 7 PCS", name: "QC AUDIT 7 PCS" },
    { code: "QC AUDIT FINISHING", name: "QC AUDIT FINISHING" },
    { code: "QC AUDIT SEWING", name: "QC AUDIT SEWING" },
    { code: "QC CHECKER FINISHING", name: "QC CHECKER FINISHING" },
    { code: "QC CUTTING", name: "QC CUTTING" },
    { code: "QC ENDLINE", name: "QC ENDLINE" },
    { code: "QC FABRIC", name: "QC FABRIC" },
    { code: "QC FABRIC INSPECTION", name: "QC FABRIC INSPECTION" },
    { code: "QC FABRIC LAB", name: "QC FABRIC LAB" },
    { code: "QC FINISHING ACCURACY", name: "QC FINISHING ACCURACY" },
    { code: "QC FINISHING ACCURASY", name: "QC FINISHING ACCURASY" },
    { code: "QC FINISHING APPEARANCE", name: "QC FINISHING APPEARANCE" },
    { code: "QC FINISHING APPEARANCE & MEANSURMENT", name: "QC FINISHING APPEARANCE & MEANSURMENT" },
    { code: "QC FINISHING BUTTON", name: "QC FINISHING BUTTON" },
    { code: "QC FINISHING MEANSURMENT", name: "QC FINISHING MEANSURMENT" },
    { code: "QC FINISHING REJECT", name: "QC FINISHING REJECT" },
    { code: "QC FINISHING WASHING", name: "QC FINISHING WASHING" },
    { code: "QC FOLDING & METAL DETECTOR", name: "QC FOLDING & METAL DETECTOR" },
    { code: "QC INLINE", name: "QC INLINE" },
    { code: "QC INTERIM AUDIT", name: "QC INTERIM AUDIT" },
    { code: "QC JSS", name: "QC JSS" },
    { code: "QC MIDLINE", name: "QC MIDLINE" },
    { code: "QC SAMPLE WORKER", name: "QC SAMPLE WORKER" },
    { code: "QC SEWING END LINE", name: "QC SEWING END LINE" },
    { code: "QC SEWING IN LINE", name: "QC SEWING IN LINE" },
    { code: "QC SEWING MID LINE", name: "QC SEWING MID LINE" },
    { code: "QC SEWING SPV", name: "QC SEWING SPV" },
    { code: "QC SUBCON", name: "QC SUBCON" },
    { code: "QC TOP SAMPLE", name: "QC TOP SAMPLE" },
    { code: "QC WASHING", name: "QC WASHING" },
    { code: "RECEPSIONIST", name: "RECEPSIONIST" },
    { code: "REJECT/PERMAK/BS", name: "REJECT/PERMAK/BS" },
    { code: "REJECT/PERMAK/BS (SPOT CLEAN)", name: "REJECT/PERMAK/BS (SPOT CLEAN)" },
    { code: "REPLACE REJECTION PANEL (BS)", name: "REPLACE REJECTION PANEL (BS)" },
    { code: "RIJECK / PERMAK / BS (Spot Clean)", name: "RIJECK / PERMAK / BS (Spot Clean)" },
    { code: "SAMPLE HELPER", name: "SAMPLE HELPER" },
    { code: "SAMPLE IRONER", name: "SAMPLE IRONER" },
    { code: "SAMPLE IRONER FULL BODY", name: "SAMPLE IRONER FULL BODY" },
    { code: "SAMPLE IRONER PANEL", name: "SAMPLE IRONER PANEL" },
    { code: "SAMPLE PLANNER", name: "SAMPLE PLANNER" },
    { code: "SAMPLING SUPERVISOR", name: "SAMPLING SUPERVISOR" },
    { code: "SAP ADMIN", name: "SAP ADMIN" },
    { code: "SAP STAFF", name: "SAP STAFF" },
    { code: "SECURITY", name: "SECURITY" },
    { code: "SENIOR MERCHANT", name: "SENIOR MERCHANT" },
    { code: "SERAT", name: "SERAT" },
    { code: "SEWING CHIEF", name: "SEWING CHIEF" },
    { code: "SEWING SUPERVISOR", name: "SEWING SUPERVISOR" },
    { code: "SHADE LOT", name: "SHADE LOT" },
    { code: "SPOT CLEAN", name: "SPOT CLEAN" },
    { code: "SPREADING", name: "SPREADING" },
    { code: "SPV STAFF HRD", name: "SPV STAFF HRD" },
    { code: "STAFF LEGAL", name: "STAFF LEGAL" },
    { code: "STAFF PAYROLL", name: "STAFF PAYROLL" },
    { code: "SUPPORT STAFF", name: "SUPPORT STAFF" },
    { code: "TECHNICAL", name: "TECHNICAL" },
    { code: "TECHNICAL SUPPORTING", name: "TECHNICAL SUPPORTING" },
    { code: "TQM ADMIN", name: "TQM ADMIN" },
    { code: "TQM CHIEF", name: "TQM CHIEF" },
    { code: "TQM STAFF", name: "TQM STAFF" },
    { code: "TRAINER", name: "TRAINER" },
    { code: "TRAINING", name: "TRAINING" },
    { code: "TRANSFER", name: "TRANSFER" },
    { code: "TRIMMING", name: "TRIMMING" },
    { code: "WASHING", name: "WASHING" },
    { code: "WASHING STAFF", name: "WASHING STAFF" },
    { code: "WFX ADMIN", name: "WFX ADMIN" },
    { code: "WH ADMIN", name: "WH ADMIN" },
    { code: "WH OPR ACCESSORIES", name: "WH OPR ACCESSORIES" },
    { code: "WH OPR FABRIC", name: "WH OPR FABRIC" },
    { code: "WH SUPERVISOR", name: "WH SUPERVISOR" },
    { code: "WH TRIMS SPV", name: "WH TRIMS SPV" },
  ],
  levels: [
    { code: "JRSTAFF", name: "Jr. Staff" },
    { code: "MDSTAFF", name: "Md. Staff" },
    { code: "OPERATOR", name: "Operator" },
    { code: "SRSTAFF", name: "Sr. Staff" },
    { code: "WORKER", name: "Worker" },
  ],
  skills: [
    { code: "A", name: "A" },
    { code: "A_PLUS", name: "A+" },
    { code: "B", name: "B" },
    { code: "B_PLUS", name: "B+" },
    { code: "C", name: "C" },
    { code: "C_PLUS", name: "C+" },
  ],
  banks: [{ code: "MANDIRI", name: "Mandiri Bank" }],
};

export const LOOKUP_SEED: Record<LookupType, SeedRow[]> = {
  CATEGORY: [
    { code: "WORKER", name: "Worker" },
    { code: "STAFF", name: "Staff" },
    { code: "EXPATRIATE", name: "Expatriate" },
  ],
  TYPE: [
    { code: "OFFICE", name: "Office Employee" },
    { code: "PROD", name: "Prod Employee" },
  ],
  SHED: [
    { code: "COMMON", name: "Common" },
    { code: "SHED_A", name: "Shed-A" },
    { code: "SHED_B", name: "Shed-B" },
    { code: "SHED_C", name: "Shed-C" },
  ],
  CONTRACT_STATUS: [
    { code: "CONTRACT", name: "Contract" },
    { code: "PROBATION", name: "Probation" },
    { code: "PERMANENT", name: "Permanent" },
  ],
  CONTRACT_CRITERIA: [
    { code: "GOOD", name: "Performance Good" },
    { code: "AVERAGE", name: "Performance Average" },
  ],
  MARITAL_STATUS: [
    { code: "MARRIED", name: "Kawin (Married)" },
    { code: "SINGLE", name: "Belum Kawin (Single)" },
    { code: "DIVORCED", name: "Cerai Hidup (Divorced)" },
    { code: "WIDOWED", name: "Cerai Mati (Divorce Death)" },
  ],
  GENDER: [
    { code: "M", name: "Male" },
    { code: "F", name: "Female" },
  ],
  PTKP: [
    { code: "TK", name: "TK" },
    { code: "K0", name: "K/0" },
    { code: "K1", name: "K/1" },
    { code: "K2", name: "K/2" },
    { code: "K3", name: "K/3" },
    { code: "TK0", name: "TK0" },
    { code: "TK1", name: "TK/1" },
    { code: "TK2", name: "TK/2" },
    { code: "TK3", name: "TK/3" },
  ],
  EDUCATION: [
    { code: "SD", name: "SD" },
    { code: "SMP", name: "SMP" },
    { code: "SMA", name: "SMA" },
    { code: "MA", name: "MA" },
    { code: "SMK", name: "SMK" },
    { code: "D1", name: "D1" },
    { code: "D2", name: "D2" },
    { code: "D3", name: "D3" },
    { code: "S1", name: "S1" },
    { code: "S2", name: "S2" },
    { code: "S3", name: "S3" },
  ],
  RELIGION: [
    { code: "HINDU", name: "Hindu" },
    { code: "ISLAM", name: "Islam" },
    { code: "KATHOLIK", name: "Katholik" },
    { code: "KRISTEN", name: "Kristen" },
  ],
  EMPLOYEE_STATUS: [
    { code: "ACTIVE", name: "Active" },
    { code: "INACTIVE", name: "Inactive" },
  ],
  BPJS_KTK: [
    { code: "ACTIVE", name: "Active" },
    { code: "INACTIVE", name: "Inactive" },
  ],
  BPJS_KES: [
    { code: "ACTIVE", name: "Active" },
    { code: "INACTIVE", name: "Inactive" },
  ],
  SERAGAM: [
    { code: "S", name: "S" },
    { code: "M", name: "M" },
    { code: "L", name: "L" },
  ],
  BLOOD_TYPE: [
    { code: "A", name: "A" },
    { code: "B", name: "B" },
    { code: "AB", name: "AB" },
    { code: "O", name: "O" },
  ],
};
