"use client";

import { useEffect, useMemo, useState } from "react";
import { PageHeader } from "@/components/layout/PageHeader";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { toast } from "sonner";

type Cell = { duration: number; estimated: number; actual: number };
type Report = { shed: string; config: { umr: number; usdRate: number; divisor: number; multipliers?: Record<string, number> }; rows: { division: string; cells: Cell[] }[] };
type Mapping = { id?: number; attendance_department: string; shed: string; division: string; display_order: number };
type Division = { id?: number; shed: string; division: string; display_order: number };
const money = (n: number) => new Intl.NumberFormat("id-ID", { maximumFractionDigits: 0 }).format(n);
const paidHours = (d: number) => 1.5 * Math.min(d, 1) + 2 * Math.max(d - 1, 0);

export default function OtPlanningPage() {
  const [tab, setTab] = useState<"report" | "reference">("report");
  const [date, setDate] = useState(new Date().toISOString().slice(0, 10));
  const [sheds, setSheds] = useState(["SHED A", "SHED B", "SHED C", "COMMON"]);
  const [data, setData] = useState<Report[]>([]); const [loading, setLoading] = useState(false);
  const [umr, setUmr] = useState(2954114); const [usdRate, setUsdRate] = useState(16000);
  const [mappings, setMappings] = useState<Mapping[]>([]); const [divisions, setDivisions] = useState<Division[]>([]);
  const [multipliers, setMultipliers] = useState<{ duration: number; paid_hours: number }[]>([]);
  async function load() { setLoading(true); try { const q = new URLSearchParams({ date }); sheds.forEach((s) => q.append("shed", s)); const r = await fetch(`/api/reports/ot-planning?${q}`); if (!r.ok) throw new Error("Gagal memuat report"); const v = await r.json(); setData(v); if (v[0]) { setUmr(v[0].config.umr); setUsdRate(v[0].config.usdRate); } } catch (e) { toast.error(e instanceof Error ? e.message : "Gagal memuat report"); } finally { setLoading(false); } }
  async function loadReferences() { const r = await fetch("/api/reports/ot-planning?references=1"); if (r.ok) { const v = await r.json(); setMappings(v.mappings ?? []); setDivisions(v.divisions ?? []); setMultipliers(v.multipliers ?? []); } }
  useEffect(() => { void load(); /* filters intentionally drive the report */ }, [date, sheds.join(",")]);
  useEffect(() => { if (tab === "reference") void loadReferences(); }, [tab]);
  const save = async () => { const values = data.flatMap((g) => g.rows.flatMap((r) => r.cells.map((c) => ({ shed: g.shed, division: r.division, duration: c.duration, person: c.estimated })))); const res = await fetch("/api/reports/ot-planning", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ date, values }) }); if (!res.ok) throw new Error("Gagal menyimpan Estimated"); toast.success("Estimated tersimpan"); };
  const update = (shed: string, division: string, duration: number, person: number) => setData((old) => old.map((g) => g.shed !== shed ? g : { ...g, rows: g.rows.map((r) => r.division !== division ? r : { ...r, cells: r.cells.map((c) => c.duration === duration ? { ...c, estimated: person } : c) }) }));
  const post = async (body: unknown) => { const r = await fetch("/api/reports/ot-planning", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body) }); if (!r.ok) throw new Error("Gagal menyimpan referensi"); await loadReferences(); };
  const exportQuery = () => { const q = new URLSearchParams({ date }); sheds.forEach((s) => q.append("shed", s)); return q.toString(); };
  return <div><PageHeader title="OT Planning" description="Perencanaan dan realisasi budget lembur per departemen." breadcrumb={[{ label: "Dashboard", href: "/dashboard" }, { label: "Report" }, { label: "OT Planning" }]} /><div className="mb-4 flex gap-2"><Button variant={tab === "report" ? "default" : "outline"} onClick={() => setTab("report")}>OT Planning Report</Button><Button variant={tab === "reference" ? "default" : "outline"} onClick={() => setTab("reference")}>Referensi</Button></div>{tab === "reference" ? <References mappings={mappings} divisions={divisions} multipliers={multipliers} umr={umr} usdRate={usdRate} setUmr={setUmr} setUsdRate={setUsdRate} date={date} post={post} /> : <><Card className="mb-4"><CardContent className="flex flex-wrap items-end gap-4 pt-6"><label>Tanggal<Input type="date" value={date} onChange={(e) => setDate(e.target.value)} /></label><span>Departemen</span>{["SHED A", "SHED B", "SHED C", "COMMON"].map((s) => <Button key={s} variant={sheds.includes(s) ? "default" : "outline"} onClick={() => setSheds((x) => x.includes(s) ? x.filter((v) => v !== s) : [...x, s])}>{s}</Button>)}<Button variant="outline" onClick={() => void save()} disabled={loading}>Simpan Estimated</Button><Button variant="outline" onClick={() => window.open(`/api/reports/ot-planning/export?${exportQuery()}`, "_blank")}>Export Excel</Button><Button variant="outline" onClick={() => window.open(`/api/reports/ot-planning/pdf?${exportQuery()}`, "_blank")}>Export PDF</Button></CardContent></Card>{loading ? <p>Memuat...</p> : data.map((g) => <ReportTable key={g.shed} group={g} update={update} />)}</>}</div>;
}

function ReportTable({ group, update }: { group: Report; update: (shed: string, division: string, duration: number, person: number) => void }) { const durations = useMemo(() => Array.from(new Set(group.rows.flatMap((r) => r.cells.map((c) => c.duration)))).sort((a, b) => a - b), [group]); const rate = (d: number) => group.config.umr / 173 * (group.config.multipliers?.[String(d)] ?? paidHours(d)); return <Card className="mb-5 overflow-auto"><CardContent className="pt-6"><h2 className="mb-3 text-lg font-semibold">{group.shed}</h2><table className="w-full min-w-[1000px] border-collapse text-sm"><thead><tr className="bg-muted"><th className="border p-2 text-left">Divisi</th>{durations.map((d) => <th colSpan={4} className="border p-2" key={d}>{d} jam<br /><span className="font-normal">Est. Orang / IDR · Actual Orang / IDR</span></th>)}<th className="border p-2">Total Est. IDR</th><th className="border p-2">Total Actual IDR</th></tr></thead><tbody>{group.rows.map((row) => <tr key={row.division}><td className="border p-2 font-medium">{row.division}</td>{durations.map((d) => { const c = row.cells.find((x) => x.duration === d) ?? { duration: d, estimated: 0, actual: 0 }; return <><td className="border p-1"><Input className="h-8 w-16" type="number" min="0" value={c.estimated} onChange={(e) => update(group.shed, row.division, d, Number(e.target.value))} /></td><td className="border p-1">{money(c.estimated * rate(d))}</td><td className="border p-1">{c.actual}</td><td className="border p-1">{money(c.actual * rate(d))}</td></>; })}<td className="border p-2">{money(row.cells.reduce((s, c) => s + c.estimated * rate(c.duration), 0))}</td><td className="border p-2">{money(row.cells.reduce((s, c) => s + c.actual * rate(c.duration), 0))}</td></tr>)}</tbody></table></CardContent></Card>; }

function References({ mappings, divisions, multipliers, umr, usdRate, setUmr, setUsdRate, date, post }: any) { const [m, setM] = useState({ attendanceDepartment: "", shed: "SHED A", division: "", displayOrder: 0 }); const [d, setD] = useState({ shed: "SHED A", division: "", displayOrder: 0 }); return <div className="grid gap-5"><Card><CardContent className="grid max-w-xl gap-4 pt-6"><label>UMR (IDR)<Input type="number" value={umr} onChange={(e) => setUmr(Number(e.target.value))} /></label><label>Kurs USD (IDR)<Input type="number" value={usdRate} onChange={(e) => setUsdRate(Number(e.target.value))} /></label><p className="text-xs text-muted-foreground">Snapshot efektif sesuai tanggal report: {date}. Pembagi tetap 173.</p><Button onClick={() => void post({ kind: "config", effectiveDate: date, umr, usdRate })}>Simpan Referensi</Button></CardContent></Card><Card><CardContent className="pt-6"><h2 className="mb-3 font-semibold">Durasi & Jam Bayar</h2><div className="grid grid-cols-2 gap-2 text-sm">{multipliers.map((x: any) => <div className="border-b p-1" key={x.duration}>{x.duration} jam → {x.paid_hours} jam-bayar</div>)}</div></CardContent></Card><Card><CardContent className="pt-6"><h2 className="mb-3 font-semibold">Mapping Departemen</h2><div className="mb-3 flex gap-2"><Input placeholder="LastDeptname attendance" value={m.attendanceDepartment} onChange={(e) => setM({ ...m, attendanceDepartment: e.target.value })} /><Input placeholder="Shed" value={m.shed} onChange={(e) => setM({ ...m, shed: e.target.value })} /><Input placeholder="Divisi" value={m.division} onChange={(e) => setM({ ...m, division: e.target.value })} /><Button onClick={() => void post({ kind: "mapping", value: m })}>Tambah</Button></div>{mappings.map((x: Mapping) => <div className="border-b p-2 text-sm" key={x.id}>{x.attendance_department} → {x.shed} → {x.division}</div>)}</CardContent></Card><Card><CardContent className="pt-6"><h2 className="mb-3 font-semibold">Master Divisi per Shed</h2><div className="mb-3 flex gap-2"><Input placeholder="Shed" value={d.shed} onChange={(e) => setD({ ...d, shed: e.target.value })} /><Input placeholder="Divisi" value={d.division} onChange={(e) => setD({ ...d, division: e.target.value })} /><Button onClick={() => void post({ kind: "division", value: d })}>Tambah</Button></div>{divisions.map((x: Division) => <div className="border-b p-2 text-sm" key={x.id}>{x.shed} → {x.division}</div>)}</CardContent></Card></div>; }
